### ISSUE TITLE
几个使用的问题

### ISSUE THREAD

**Issue by fscarmen** [xiaozhou26/gh-proxy-pro#2]
很感谢你的项目，部署和使用中发现一些疑问请教一下
1. 代码里的以下有个网有什么用的？
 https://github.com/xiaozhou26/gh-proxy-pro/blob/eaf19ce48450c933907b127cf58dbbb5c602a7cd/index.js#L5

2.部署时发现要先加环境变量，否则部署时出错说缺少 GH_URLS 还是 TARGET_URLS，导致不成功的。

<img width="1330" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/11f16f66-e647-402c-9eb7-0fd09184b87a">

3.在使用中发现都是用到 jsd.cdn.zzko.cn 这个网，但该网不支持 IPv6 only 的机器，如何处理？（ IPv4 机器是正常的）

<img width="1122" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/ccfaa7a5-3df2-443e-a80d-ae7103775284">

4.环境变量里是设置项目里的相应文件里的值吗？

<img width="1202" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/e5455c08-99b0-4e0c-bd66-e3423a6c5d51">

**Comment by xiaozhou26** [comment]
1.这个项目基于gh-proxy是前后端分离的，这个网站是静态前端
2.readme里面好像写了
3.我记得这个公益服务有ipv6，国内访问有，但是国外可能重定向别的镜像站了
4.是

**Comment by fscarmen** [comment]
> 2.readme里面好像写了

我是有看，不过没有细看要先添加环境变量先，这个小问题。

> 3.我记得这个公益服务有ipv6，国内访问有，但是国外可能重定向别的镜像站了

这个有没有好办法处理一下，使用 github 代理有目的之一，就是让 IPv6 only 的机器能下载到 github 的文件。
现在我只能先用 dns64 处理，通过那些网站的 nat64 服务

**Comment by xiaozhou26** [comment]
> > 2.readme里面好像写了
> 
> 我是有看，不过没有细看要先添加环境变量先，这个小问题。
> 
> > 3.我记得这个公益服务有ipv6，国内访问有，但是国外可能重定向别的镜像站了
> 
> 这个有没有好办法处理一下，使用 github 代理有目的之一，就是让 IPv6 only 的机器能下载到 github 的文件。 现在我只能先用 dns64 处理，通过那些网站的 nat64 服务

问题3你有没有什么想法吗？可以说一下

**Comment by xiaozhou26** [comment]
> > 2.readme里面好像写了
> 
> 我是有看，不过没有细看要先添加环境变量先，这个小问题。
> 
> > 3.我记得这个公益服务有ipv6，国内访问有，但是国外可能重定向别的镜像站了
> 
> 这个有没有好办法处理一下，使用 github 代理有目的之一，就是让 IPv6 only 的机器能下载到 github 的文件。 现在我只能先用 dns64 处理，通过那些网站的 nat64 服务

https://jsd.cdn.zzko.cn/19.html

**Comment by xiaozhou26** [comment]
> > 2.readme里面好像写了
> 
> 我是有看，不过没有细看要先添加环境变量先，这个小问题。
> 
> > 3.我记得这个公益服务有ipv6，国内访问有，但是国外可能重定向别的镜像站了
> 
> 这个有没有好办法处理一下，使用 github 代理有目的之一，就是让 IPv6 only 的机器能下载到 github 的文件。 现在我只能先用 dns64 处理，通过那些网站的 nat64 服务

或者改回cdn.jsdelivr.net

**Comment by fscarmen** [comment]
### 我用一台 IPv6 only 的机器，dns 是 google 的，查了所有的 TARGET_URLS.txt 里的代理，我只测 v6 的，因为v6支持的话，几乎都会同时支持 v4 的，反之则不然。把符合条件的放在 yes ，不符合条件的放在 no

```
GH_PROXY=("https://cdn2.fscarmen.workers.dev" "https://gh.duckcc.com" "http://117.23.191.83:2000" "https://185.184.223.221" "http://45.76.193.176" "http://119.28.4.250" "https://54.95.106.156" "http://101.32.203.140:666" "http://124.156.158.242:4000" "http://130.162.130.196" "http://141.147.170.49" "https://x.whereisdoge.work" "http://x.whereisdoge.work" "https://43.154.123.246" "http://183.252.47.246:666" "https://38.47.124.28" "https://8.218.216.196" "http://141.147.171.213:8888" "https://gh.222322.xyz" "http://gh.222322.xyz" "https://91.199.209.217" "http://152.32.220.159:8888" "http://8.222.225.40:8888" "http://138.2.24.229:8888" "http://43.159.61.252:9000" "http://168.138.50.197:8888" "http://185.184.223.102:8880" "http://8.210.207.225:8888" "http://42.193.4.156:8880" "http://185.242.233.179:8118" "http://8.210.153.246:9000" "http://5.255.108.100:81" "http://118.195.174.59:8800" "http://config.galaxy-cloud.com" "https://config.galaxy-cloud.com" "https://23.26.223.55" "http://45.78.20.18:90" "http://178.157.94.137:8080" "http://151.248.68.37:8080" "http://136.243.215.211:12345" "http://152.69.198.119:8000" "http://152.67.215.57:8081" "http://114.221.171.124:8020" "http://74.48.108.189:10088" "http://43.129.191.251:8088" "http://8.217.227.38:5566" "http://138.2.123.193:8090" "https://155.248.173.179" "http://8.219.112.168:10000" "http://165.154.71.248:10001" "https://ghproxy.moeio.org" "http://ghproxy.moeio.org" "https://193.122.115.49" "http://g.blfrp.cn" "https://g.blfrp.cn" "http://38.207.175.88:8080" "http://43.135.0.252:8080" "http://43.163.237.51:8080" "http://v2gh.b-cdn.net" "http://91.199.209.233:3002" "https://202.61.246.52" "http://47.243.96.226:8080" "http://quick.imfht.com:81" "http://154.12.55.10:9988" "http://152.67.215.236:12345" "http://45.149.156.201:7080" "http://39.106.168.34" "http://58.243.36.177:9000" "http://43.133.162.210:9000" "http://212.50.233.214:8888" "http://8.217.145.216:9000" "http://152.70.36.140:88" "http://101.32.18.93:88" "http://154.12.38.21:81" "http://43.132.227.252:9090" "http://47.245.88.61" "http://c0b0109d9439de57fe3c.ljw.ink" "https://123.58.210.249" "https://c0b0109d9439de57fe3c.ljw.ink" "http://43.155.169.157" "http://134.209.150.194:7005" "http://23.247.138.54:8087" "http://43.159.50.131:8008" "http://202.61.246.52:8000" "http://149.104.15.159:3000" "http://47.109.58.212:8082" "http://52.221.203.212" "http://140.238.33.157:3000" "http://38.47.124.28:18080" "http://47.236.114.62:18080" "http://155.248.180.127:3000" "http://74.48.174.94:8080" "http://47.243.163.102:10086" "https://129.154.50.170" "http://152.70.97.166:1234" "https://kr-gh.zhetengsha.eu.org" "http://164.152.34.35:81" "http://43.154.105.8:8888" "http://www.tticloud.top:3000" "http://13.230.117.137:8008" "http://82.157.146.148:9001" "http://158.180.92.175:8000" "http://193.151.183.223:8088" "https://jp.aning666.top" "http://jp.aning666.top" "http://124.156.171.217:32769" "http://193.142.59.42" "http://152.70.94.22:9080" "https://github.xxlab.tech" "http://github.xxlab.tech" "https://140.238.18.229" "https://158.101.139.22" "https://146.56.114.218" "https://45.66.129.222" "https://github.chenc.dev" "http://43.154.123.246" "http://51.195.241.253:8080" "http://43.153.184.91:10000" "http://git.gushao.club" "https://git.gushao.club" "http://152.67.219.235:8989" "http://www.subook.link:88" "http://138.2.54.229:12580" "http://138.2.118.77" "http://138.2.69.119:30001" "http://140.238.158.156:9010" "http://45.78.18.183:8022" "http://94.74.100.230:9010" "https://github.muou666.com" "http://141.11.209.113:8070" "http://git.40609891.xyz" "https://git.40609891.xyz" "http://git.19970301.xyz" "http://git.669966.xyz" "http://blog.whereisdoge.work" "http://hy.whereisdoge.work" "http://a.whereisdoge.work" "https://jp-cdn.andiest.com" "http://158.101.139.22:9999" "http://158.101.152.90:8123" "https://github.7boe.top" "http://api2.qbot.xuanimage.top" "https://gh.nxnow.top" "https://ghproxy.cianogame.top" "http://103.177.248.14:12345" "https://gh.lfh.ee" "https://hk.moran233.xyz" "http://140.238.17.136:9980" "https://ghproxy.markxu.online" "http://120.79.140.163:6021" "http://111.229.117.180:2068" "https://jp4.judi.fun" "https://jp5.judi.fun" "http://101.43.36.238:4080" "http://165.154.148.121:7890" "https://gh.catmak.name" "http://43.163.230.97:800" "https://bt.moran233.xyz" "https://www.gh.mirror.ct8.pl" "https://githubapi.jjchizha.com" "https://cpcontacts.whereisdoge.work" "http://cpcalendars.huluobo.ltd" "http://cpcalendars.whereisdoge.work" "http://autodiscover.whereisdoge.work" "http://webdisk.whereisdoge.work" "https://webdisk.whereisdoge.work" "http://smtp.whereisdoge.work" "https://smtp.whereisdoge.work" "https://cpanel.whereisdoge.work" "http://cpanel.whereisdoge.work" "https://mail.whereisdoge.work" "http://mail.whereisdoge.work" "http://mail.huluobo.ltd" "http://huluobo.ltd" "http://hk.rmysh.com" "http://sramd.vvvvv.eu.org:9080" "http://zipchannel.top:4000" "http://mysql.ofnhkb1.com" "https://32618.jkjoy.cn" "https://gh.linuxba.com" "https://clone.tapoop.com" "https://ql.133.info" "http://txhk.168828.xyz:8088" "http://webdav.camus.xyz" "https://85823.jkjoy.cn" "http://xxqg.168828.xyz:8088")

for i in ${GH_PROXY[@]}; do { [ $(curl -6 -I -w %{http_code} -o /dev/null -skL --connect-timeout 2 --retry 2 ${i}/https://raw.githubusercontent.com/xiaozhou26/gh-proxy-pro/main/README.md) = '200' ] && echo $i >> yes || echo $i >> no; }&; done
```

### cat yes 文件，在 186 个代理中，有以下的是支持 v6 的，项目能否把这些和你上面提到的 cdn.jsdelivr.net 放到开头的优先使用的？？？
```
http://v2gh.b-cdn.net
http://git.gushao.club
https://git.gushao.club
http://git.669966.xyz
https://jp-cdn.andiest.com
https://jp4.judi.fun
```

### 1. 用另一台 v4 only 的机器测，其实也有一些代理网不能失效的了，具体没有逐一试了。2.测试的机器是墙外的，所以上面符合条件的在墙内被封也有可能。

**Comment by fscarmen** [comment]
在 https://ipw.cn/ipv6webcheck/ 查，只有第一个查不出来，不知道是被墙还是网站限制了
<img width="803" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/39d80f75-634b-4ab9-8057-0e7ab88a7964">
<img width="797" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/af0f1e80-9496-4786-984d-1284dcd6dc99">
<img width="785" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/8d2f21cb-25c2-41a0-a325-0016a7df1399">
<img width="790" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/09bab615-6b11-42bd-9983-0ca29ec1d6f4">
<img width="862" alt="image" src="https://github.com/xiaozhou26/gh-proxy-pro/assets/62703343/6d3005ba-13a8-4fcb-be6e-670708997ea6">

**Comment by xiaozhou26** [comment]
> 在 https://ipw.cn/ipv6webcheck/ 查，只有第一个查不出来，不知道是被墙还是网站限制了 <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/62703343/316531118-39d80f75-634b-4ab9-8057-0e7ab88a7964.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzg4NzIsIm5iZiI6MTcxMTM3ODU3MiwicGF0aCI6Ii82MjcwMzM0My8zMTY1MzExMTgtMzlkODBmNzUtNjM0Yi00YWI5LTgwNTctMGU3YWI4OGE3OTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkYjNlZjkzMzVkNWY0NTZkZDI0NDY0MWQxZTkyMzQ4ZGYwMGNkNmQ1NTA5YWQyYjY5Y2Q5OTdmZWJjY2JiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PTazBtYRfDhMrIEDCrl99mXES9BG2dWu6gJlqAfK0qs"> <img alt="image" width="797" src="https://private-user-images.githubusercontent.com/62703343/316529724-af0f1e80-9496-4786-984d-1284dcd6dc99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzg4NzIsIm5iZiI6MTcxMTM3ODU3MiwicGF0aCI6Ii82MjcwMzM0My8zMTY1Mjk3MjQtYWYwZjFlODAtOTQ5Ni00Nzg2LTk4NGQtMTI4NGRjZDZkYzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OTBlM2I2NDAwM2I2OGQ1MWNjMDk0YmE5NDAyMDY5ZGVmODczNjk1NTEyYmZhMzY0ZWY4M2MyYjM3NjE5YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.giIfyN0VVrfGVTPopr2xut6Wx-yOLHRuKXO_W24Zi5M"> <img alt="image" width="785" src="https://private-user-images.githubusercontent.com/62703343/316529942-8d2f21cb-25c2-41a0-a325-0016a7df1399.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzg4NzIsIm5iZiI6MTcxMTM3ODU3MiwicGF0aCI6Ii82MjcwMzM0My8zMTY1Mjk5NDItOGQyZjIxY2ItMjVjMi00MWEwLWEzMjUtMDAxNmE3ZGYxMzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZGZlMmUxNTg4YTI2YTRiMjQ2MDMzOWQ4ZDIzODJjM2UxMWJmZjI2MzEzOWZiZDhjZWJjOTliM2Y0ODk2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-7ByS_6Lxtbc-53YS95-D9acfHyo9oL2g6I09TcZ4UM"> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/62703343/316530620-09bab615-6b11-42bd-9983-0ca29ec1d6f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzg4NzIsIm5iZiI6MTcxMTM3ODU3MiwicGF0aCI6Ii82MjcwMzM0My8zMTY1MzA2MjAtMDliYWI2MTUtNmIxMS00MmJkLTk5ODMtMGNhMjllYzFkNmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NjIyNzA2NWYzYjJhMzU4OTlmNGVjYTE5ZTlmOTQ3Y2NkYzVlY2JhYjRjMWQzNDFhZmMxMjEzMGQxNmMyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T0pK52rmwoMdyECAPxDHrk3mQR5EjO4N7ucqrpqV9sc"> <img alt="image" width="862" src="https://private-user-images.githubusercontent.com/62703343/316530881-6d3005ba-13a8-4fcb-be6e-670708997ea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzg4NzIsIm5iZiI6MTcxMTM3ODU3MiwicGF0aCI6Ii82MjcwMzM0My8zMTY1MzA4ODEtNmQzMDA1YmEtMTNhOC00ZmNiLWJlNmUtNjcwNzA4OTk3ZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0NTYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzc0NjUwYzgxNGQ1ODM2N2UwOWNhYzE3ZDFjNjEyN2UzMTk5M2NkOWEwMzk2MjAyZDRmMDIxNTljNmU0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._5v_S4BKRUm1K4V9tLO-2crHamS-kGmpF3UPsDHoLSM">

这个公共服务应该是限制了

**Comment by xiaozhou26** [comment]
它这个公共服务国外是直接用vercel加速的，你有需要可以直接换成官方的fastly.jsdelivr.net就行了

**Comment by fscarmen** [comment]
最早我是用jsdelivr.net ,ghproxy.com 等公开的网，后面总是遇到不稳定的情况而炸锅。
后面我就自己弄worker反代，稳定是稳定了，但官方限制每天10w，我被用户撸到 120w，超了11倍，而且连接数还在升，虽然也没有影响，还是担心日后难说，所以停了，在找其他稳定的替代方案。

**Comment by xiaozhou26** [comment]
> 最早我是用jsdelivr.net ,ghproxy.com 等公开的网，后面总是遇到不稳定的情况而炸锅。 后面我就自己弄worker反代，稳定是稳定了，但官方限制每天10w，我被用户撸到 120w，超了11倍，而且连接数还在升，虽然也没有影响，还是担心日后难说，所以停了，在找其他稳定的替代方案。

😨，你扫的那几个站点也多半是cf worker搭建的，因为直接有ipv6还是cf 段的，流量还是会超的，jsdelivr国外也会炸吗，国外其实GitHub raw也行，GitHub现在支持ipv6了

**Comment by xiaozhou26** [comment]
> 最早我是用jsdelivr.net ,ghproxy.com 等公开的网，后面总是遇到不稳定的情况而炸锅。 后面我就自己弄worker反代，稳定是稳定了，但官方限制每天10w，我被用户撸到 120w，超了11倍，而且连接数还在升，虽然也没有影响，还是担心日后难说，所以停了，在找其他稳定的替代方案。

😨，你扫的那几个站点也多半是cf worker搭建的，因为直接有ipv6还是cf 段的，流量还是会超的，jsdelivr国外也会炸吗，国外其实GitHub raw也行，GitHub现在支持ipv6了

**Comment by fscarmen** [comment]
> 😨，你扫的那几个站点也多半是cf worker搭建的，因为直接有ipv6还是cf 段的，流量还是会超的，jsdelivr国外也会炸吗，国外其实GitHub raw也行，GitHub现在支持ipv6了

还真遇到过啊 jsdelivr 炸。
上一两年 https://raw.githubusercontent.com 已经支持 IPv6  了。只是有的项目给国内机器用，所以需要代理。

**Comment by xiaozhou26** [comment]
> > 😨，你扫的那几个站点也多半是cf worker搭建的，因为直接有ipv6还是cf 段的，流量还是会超的，jsdelivr国外也会炸吗，国外其实GitHub raw也行，GitHub现在支持ipv6了
> 
> 还真遇到过啊 jsdelivr 炸。 上一两年 https://raw.githubusercontent.com 已经支持 IPv6 了。只是有的项目给国内机器用，所以需要代理。

可以国内走公益站，国外走GitHub

**Comment by xiaozhou26** [comment]
国外ipv6已支持

**Comment by fscarmen** [comment]
正，好啊
